import { DistanceFn } from './metrics';
import { kmeans, computeCentroids } from './kmeans';

const MIN_SPLIT_SIZE = 4;

/**
 * Computes the log-likelihood of a cluster under a spherical Gaussian model.
 * Used by X-Means to decide whether splitting a cluster improves the fit.
 *
 * The model assumes each cluster is generated by a Gaussian with:
 *   - mean = centroid
 *   - variance = average squared distance from centroid
 */
function clusterLogLikelihood(vectors: number[][], centroid: number[], distFn: DistanceFn): number {
	const n = vectors.length;
	if (n <= 1) return 0;

	const dim = centroid.length;

	let variance = 0;
	for (const vec of vectors) {
		const d = distFn(vec, centroid);
		variance += d * d;
	}
	variance /= n;

	// Avoid log(0) for perfectly clustered data
	if (variance <= 1e-15) return 0;

	// Log-likelihood under spherical Gaussian:
	// L = -n/2 * log(2π) - n*dim/2 * log(σ²) - n/2
	const logLikelihood = (-n / 2) * Math.log(2 * Math.PI) - ((n * dim) / 2) * Math.log(variance) - n / 2;

	return logLikelihood;
}

/**
 * Computes BIC (Bayesian Information Criterion) for a model.
 * Lower BIC is better (penalizes model complexity).
 * BIC = -2 * logLikelihood + numParams * log(N)
 */
function bic(logLikelihood: number, numParams: number, n: number): number {
	return -2 * logLikelihood + numParams * Math.log(n);
}

/**
 * X-Means clustering: extends K-Means with BIC-based cluster splitting
 * to automatically determine the optimal number of clusters.
 *
 * Algorithm:
 *   1. Start with K_min clusters using K-Means
 *   2. For each cluster, try splitting into 2 sub-clusters
 *   3. If splitting reduces BIC, keep the split
 *   4. Repeat until K_max is reached or no more splits improve BIC
 *
 * @param vectors  Input data points (N x D)
 * @param K_min    Minimum number of clusters (default: 2)
 * @param K_max    Maximum number of clusters (default: 10)
 * @param distFn   Distance function
 * @param seed     Seed for reproducibility
 * @returns        Cluster assignments (length N, values 0..K-1)
 */
export function xmeans(vectors: number[][], K_min: number, K_max: number, distFn: DistanceFn, seed: number): number[] {
	const n = vectors.length;
	if (n === 0) throw new Error('Cannot cluster empty input');
	if (K_min <= 0) throw new Error('K_min must be positive');
	if (K_max < K_min) throw new Error('K_max must be >= K_min');

	if (K_min >= n) return vectors.map((_, i) => i);

	const dim = vectors[0].length;
	let currentK = Math.min(K_min, n);
	let assignments = kmeans(vectors, currentK, distFn, seed);

	// Iteratively try to split clusters
	let improved = true;
	while (improved && currentK < K_max) {
		improved = false;
		const centroids = computeCentroids(vectors, assignments, currentK);

		// Group vectors by current cluster
		const clusterVectors = new Map<number, { indices: number[]; vecs: number[][] }>();
		for (let i = 0; i < n; i++) {
			const c = assignments[i];
			if (!clusterVectors.has(c)) clusterVectors.set(c, { indices: [], vecs: [] });
			const group = clusterVectors.get(c)!;
			group.indices.push(i);
			group.vecs.push(vectors[i]);
		}

		// Track how assignments get remapped after splits
		const newAssignments = [...assignments];
		let nextClusterId = currentK;

		for (const [clusterId, group] of clusterVectors) {
			if (currentK >= K_max) break;
			if (group.vecs.length < MIN_SPLIT_SIZE) continue;

			// Parent BIC: model this cluster as a single Gaussian
			const parentLL = clusterLogLikelihood(group.vecs, centroids[clusterId], distFn);
			// Parameters: dim values for the centroid + 1 for variance
			const parentBIC = bic(parentLL, dim + 1, group.vecs.length);

			// Try splitting into 2 sub-clusters
			const subAssignments = kmeans(group.vecs, 2, distFn, seed + clusterId);
			const subCentroids = computeCentroids(group.vecs, subAssignments, 2);

			// Children BIC: sum of log-likelihoods for each sub-cluster
			let childrenLL = 0;
			for (let sc = 0; sc < 2; sc++) {
				const subVecs = group.vecs.filter((_, i) => subAssignments[i] === sc);
				if (subVecs.length > 0) {
					childrenLL += clusterLogLikelihood(subVecs, subCentroids[sc], distFn);
				}
			}
			// Parameters: 2 centroids + 2 variances
			const childrenBIC = bic(childrenLL, 2 * (dim + 1), group.vecs.length);

			// Lower BIC = better model. Split if children model is better.
			if (childrenBIC < parentBIC) {
				improved = true;
				currentK++;

				// Remap: sub-cluster 0 keeps original ID, sub-cluster 1 gets new ID
				for (let i = 0; i < group.indices.length; i++) {
					if (subAssignments[i] === 1) {
						newAssignments[group.indices[i]] = nextClusterId;
					}
				}
				nextClusterId++;
			}
		}

		if (improved) {
			assignments = newAssignments;

			// Renumber clusters to be contiguous (0, 1, 2, ...)
			const uniqueIds = [...new Set(assignments)].sort((a, b) => a - b);
			const idMap = new Map<number, number>();
			uniqueIds.forEach((id, idx) => idMap.set(id, idx));
			assignments = assignments.map((a) => idMap.get(a)!);
			currentK = uniqueIds.length;
		}
	}

	return assignments;
}
